### ISSUE TITLE
PARTNER PAGE : add a legend to reporting heatmap 

### ISSUE THREAD

**Issue by paulgirard** [medialab/ricardo#104]

**Comment by sim51** [comment]
See  e05db3936c836591ee36a3d1e26d76f3b46f9ef2

**Comment by sim51** [comment]
Need to review the wording for the french version, and to do the english one.

- PARTNER_HEATMAP_LEGEND_FADEIN
- PARTNER_HEATMAP_LEGEND_PERCENTIL
- PARTNER_HEATMAP_LEGEND_PERCENTIL_1
- PARTNER_HEATMAP_LEGEND_PERCENTIL_2
- PARTNER_HEATMAP_LEGEND_PERCENTIL_3
