### ISSUE TITLE
Add main selectors in page title in WORLD, PARTNER, BILATERAL

### ISSUE THREAD

**Issue by paulgirard** [medialab/ricardo#106]
World : dates
partner : partner + dates
bilateral : reporting1 reporting 2 and dates
exchagne rate : reference currency

See Reporting as example

**Comment by sim51** [comment]
Done in ee0c1aa3b5d65a4e8f77e6cf2ba968552056e5c1 & e0d3f3add201d66aaf92658f2ca0c9aa35995988

**Comment by sim51** [comment]
Now, we need to review all the dataviz for the time period

**Comment by sim51** [comment]
For the same range of dates on all dataviz, see commit 07f216899560cdeb751442825dcac4c4b606dbad
