### ISSUE TITLE
add dependency tree for reporting entities in metadata view

### ISSUE THREAD

**Issue by katossky** [medialab/ricardo#46]
On this view, it is not clear what is a country, what is a town, what is a state inside a country...

![image](https://cloud.githubusercontent.com/assets/13658517/24190190/1f9c57f8-0ee8-11e7-921c-b9954ca04f9b.png)

It looks like some dependency tree / comments would help to understand the link between the entities. For instance, is Algeria is included into the French statistics until the independence? Is Hamburg included in Germany?

I am not sure what is the best way to visualize it... a color scheme? (a color for an independent state, an other for dependent region, and so on until the last level of the hierarchy is reached) But this does not help to know which entity a given sub-entity belongs to. A tree scheme? But the problem is that some countries may have been dependent at some point and have become independent (or the reverse). Icons? That could help to tell appart towns from provinces from countries... but what about a state-city?

Do you have any suggestions? I have no doubts these are important meta-data one has to represent in some way.

**Comment by paulgirard** [comment]
The entities in RICardo are indeed very heterogeneous !

On the metadata view one can choose to color the entities not by sourceType (by default) but by entityType as shown here :

![image](https://cloud.githubusercontent.com/assets/193478/24249138/6b705126-0fd2-11e7-9756-3754103d8e0a.png)

This being said, we identified the lack of documentation about our entities database.
As you proposed it would be better to show how we classified the entities and the information we have about them. We might add this in a near future as a separate view.

To answer you question about Algeria.
The entities are the name which were found in the trade sources.
Having Algeria in the list of reporting means some source report Algerian trade separately from France.

The answer to "is the Algerian trade included in the French trade ?" is No.
But there is no other ways than reading the source to answer this kind of question.
And we haven't this info in the database yet.

It's precisely one of the many issues about this work.
It's already a nice thing that the metadata view brings you the question.
We would have to work much more to identify political links between entities through time in the database and even more to make use of those data in the visualisations.
We hope to find time and solution to tackle this issue.

Thank you very much for your comment.

**Comment by katossky** [comment]
Thanks for your time!

Can it not be done through crowdsourcing? I mean, it would be very tedious for 1 person to read all the documentation, but for 1 specialist of 1 country, it would be like just normal simple work to do. You "just" have to allow each person visiting your website to help in regard to this issue.

**Comment by katossky** [comment]
And sorry, I did not see that it was possible to change color.
