### ISSUE TITLE
CODE: update deps management and the building process

### ISSUE THREAD

**Issue by paulgirard** [medialab/ricardo#72]
- [x] migrate dependencies in npm (replace static imports)
- [x] migrate/clean the build process
- [x] check data build process documentation
- [x] test some deps updates

**Comment by sim51** [comment]
From my POV, it's done even if we need to : 

- [ ] Refacto the documentation
- [ ] Make regression test, ie to see if I have broken something

**Comment by sim51** [comment]
Code minification is implemented now in the build process
