### ISSUE TITLE
Political status API

### ISSUE THREAD

**Issue by paulgirard** [medialab/ricardo#74]
- [ ] add GPH_ID in RICentities route response
- [ ] add a  new political status route
/political_status/GPH_ID

GPH_ID : GeoPolitical ID used in the GeoPolHist dataset

This route gathers data from DGPEW dataset to create the political status timeline of the country view.
The qualitative data (name, status) will be used to create a tooltip on top of the timeline.
Data aggregation through time could be done server-side to be discussed.
see 

```json
{
    "slug": "Canada",
    "GPE_ID": 123,
    "nonSovereignPeriods": [
        {"sovereign": {"name":"France", "GEP_ID": 45},"status": "became colony of", "startYear":1888, "endYear":1890},
        {"sovereign": { "name": "United Kingdom" , "GEP_ID": 3}, "status": "became part of", "startYear":1890, "endYear":1896}
    ],
    "sovereignOf": [
        {"dependency": {"name":"Ontario", "GPE_ID": 256}, "status": "became colony of", "startYear":1888, "endYear":1890},
        {"dependency": {"name":"Québec", "GPE_ID": 324}, "status": "became part of", "startYear":1870, "endYear":1896}
    ]
}
```

**Comment by paulgirard** [comment]
The GeoPolHist dataset is actually a 200ko CSV file.
It will be hosted in a different repository (#76).
I am not sure we actually need an API. We could use the complete csv directly or compute by entity json static files published along-side the GeoPolHist visual tool.
To be discussed.

**Comment by paulgirard** [comment]
We will integrate GeoPolHist data into RICardo's API at build and add an API route.

**Comment by jacomyal** [comment]
I'll start with just hard copying (and committing, temporarily) the CSV files from medialab/ric_entities_timelines into the `client/src/public/data` folder.

**Comment by sim51** [comment]
Regarding the volumetry and the fact that we need all the data,  reading the CSV files is enough (keep its simple ..).
In the commit a60fb28 I integrated the download of the CSV files in the build process.
