### ISSUE TITLE
Political status timeline in country view

### ISSUE THREAD

**Issue by paulgirard** [medialab/ricardo#75]
This is a mockup done by editing the actual HTML:
![image](https://user-images.githubusercontent.com/193478/87171903-a926c600-c2d3-11ea-9ede-4fb612517880.png)

- [x] move the data availability lines just underneath the main curve horizontal axe keeping the brush feature removing title and legend (legend already complete). This visual helps when beginning of curves are hard to distinguished from horizontal axe
- [x] reuse the container row div #countryBrushing  to add the political status timeline (rename the id)

The political status block is composed of 
- a title + link to GeoPolHist dataviz exploration with a better "external link" icon

- a visualisation timeline with number of dependencies curve + vertical axe + "not sovereign" periods represented as a grey scale ? overlay 
![image](https://user-images.githubusercontent.com/193478/87176302-353bec00-c2da-11ea-84cb-c86bbb664e3b.png)

- Legend : " - number of entities controlled by Finland [ ] period when Finland is not sovereign"
- a final note : "Note that reporting trade statistics generally does not include trade with dependencies which are registered as trade partners"

Text will be adjusted with Béatrice directly when first version ready.

Data to feed the new visualisation block comes from a new API point to be added #74

**Comment by jacomyal** [comment]
About the `removing title and legend (legend already complete` in the first task, I have to let it, or once the user uses the brush, he loses the global timeline caption.

**Comment by jacomyal** [comment]
A first version has been pushed to the `ow-updates` branch. The tooltips are just native `title` elements, but it works and is a solid first version.
