### ISSUE TITLE
Exchange rates page

### ISSUE THREAD

**Issue by paulgirard** [medialab/ricardo#80]
- [x] Exchange rates title
- [x] paragraph of explanation
- [x] main block title + selector: Rates to [select reference currency default to pound sterling] variations
- [x] sort by selector : minimum average of 1-rate (first the currency of relative same value),  alphabetic, ?
- [x] filter field on currency name
- [x] small multiple of exchange rates curves independent scales, scale min = minimum rate and not zero to save height and because we are interested in variations not in absolute value of rates.
- [ ] ~~tooltip on currency name displaying the list of reporting using it ?~~

**Comment by jacomyal** [comment]
No way currently to retrieve the list of reporting using a currency. This last task is delayed to "later".

**Comment by jacomyal** [comment]
A first version has been pushed to the `ow-updates`. It is pretty basic, but implements each of the cited features.
